0815
QingRiver/fish pull request #12
Opened 2021-08-15 16:04 UTC by OliviaC1024

2021-08-15 16:07 UTC, OliviaC1024 commented
unit2

2021-08-17 10:37 UTC, kscarrot requested changes
done

2021-08-17 10:37 UTC, kscarrot commented on src/unit2/no03_split.js
> +  let res = resArr[2] + '年' + resArr[0] + '月' + resArr[1] + '日'
此处用模板字符串会更好 
```JavaScript
let res = `${resArr[]2}年${resArr[0]}月${resArr[1]}日`
```

2021-08-17 10:37 UTC, kscarrot commented on src/unit2/no04_reduce.js
> +    if (word in allwords) allwords[word]++
对象不用`in`的话可以直接
```JavaScript
if (allwords[word]) { }
```

2021-08-17 10:37 UTC, kscarrot commented on src/unit2/no04_reduce.js
> +    if (word in allwords) allwords[word]++
把对象当成数组来理解,变量的时候用 方括号, 常量用 .号

2021-08-17 10:37 UTC, kscarrot commented on src/unit2/no05_sort.js
> +  const sortVal = { '🍎': 2, '🍌': 1 }
good!

2021-08-17 10:37 UTC, kscarrot commented on src/unit2/no07_application2.js
> +export const getVipBillList = (billLists, vipList) => {
此处可以链式处理,逻辑会比较干净

2021-08-19 06:31 UTC, OliviaC1024 commented
lgtm

2021-08-19 06:43 UTC, OliviaC1024 reviewed
lgtm

2021-08-20 15:34 UTC, kscarrot approved these changes

2021-08-20 15:35 UTC, kscarrot commented on src/unit2/no01_map.test.js
> +    ).toStrictEqual([297, 0, 240])
单测写错了

2021-08-20 15:35 UTC, kscarrot commented on src/unit2/no04_reduce.js
> +  return numberList.reduce((acc, cur) => acc + cur, 0)
这里单测不过是因为我穿了个空数组,要赋初始值0

2021-08-20 15:36 UTC, kscarrot commented on src/unit2/no05_sort.js
> -    return test[el.index]
错了一点点哈...问题不大  上下文没有这个test

2021-08-20 15:36 UTC, kscarrot commented on src/unit2/no05_sort.js
> -    return test[el.index]
不报错是因为单测里有同名的test...

2021-08-20 15:38 UTC, kscarrot commented on src/unit2/no07_application2.js
> +    .map((billList) => `${billList.name}:${billList.cart.reduce(sumCart, 0)}元`)
可以看一下这里的优化思路
1. 数组是支持链式调用的,`filter`,`map`这种得到的结果还是数组,所以可以继续用下去,实际开发过程中数据量没那么大,可以使用小步快跑的方式,每一行执行一个功能,这样比较好调试,也好理解
2. `reduce`实际上语义是折叠,比如求和,比如算账,比如把一堆数组连成一个大数组,可以自己体会一下`reduce`和`map`的差别
3. 使用模板字符串可以避免字符串的拼接,也会更加好看

2021-08-20 15:39 UTC, kscarrot commented
good

2021-08-20 15:39 UTC, merged